services:

    bot:
        build: .
        env_file:
            - ./.env
        restart: always
        image: maxlethal/timemachine
        container_name: timemachine
        volumes:
            -   tm_vol:/app/graphs/

volumes:
    tm_vol:
